import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner.component";
import Card from "../components/card/card.component";
import {fetchCoffeeStores} from "../lib/coffee-store";
import userTrackLocation from '../hooks/user-track-location.hooks';
import {useEffect, useState} from "react";


export async function getStaticProps(context) {
    const coffeeStoresData = await fetchCoffeeStores();

    return {
        props: {
            coffeeStores: coffeeStoresData
        }
    }

}

export default function Home({coffeeStores}) {
    const [coffeeStoresFromState, setCoffeeStores] = useState("");
    const [coffeeStoresError, setCoffeeStoresError] = useState(null);

    const {locationErrorMessage, handleTrackLocation, latLong, isFindingLocation} = userTrackLocation();
    const handleOnBannerButtonClick = () => {
        console.log("Banner Button Clicked");
        handleTrackLocation();
    };
    useEffect(async () => {

        if (latLong) {
            try {
                const data = await fetchCoffeeStores(latLong, 12);
                setCoffeeStores(data);
            } catch (error) {
               setCoffeeStoresError(error.message)
            }
        }


    }, [latLong])
    return (
        <div className="home-page">
            <Head>
                <title>Coffee connoisseur</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="home-page__main">
                <Banner
                    buttonText={isFindingLocation ? "Locating..." : "View Stores nearby"}
                    handleOnClick={handleOnBannerButtonClick}
                />
                {
                    locationErrorMessage && <p>Something went Wrong:{locationErrorMessage}</p>
                }
                {
                    coffeeStoresError &&  <p>Something went Wrong:{coffeeStoresError}</p>
                }
                <div className="hero-image">
                    <Image src={"/static/coffee.png"} width={512} height={512} alt={"hero image"}/>
                </div>
                <h2 className="heading-secondary">Colombo Coffee Shops</h2>
                <div className="card-layout m-t-4 ">
                    {
                        coffeeStores.map(
                            ({id, name, imageUrl}) => (
                                <Card key={id} name={name} href={`/coffee-store/${id}`}
                                      imageUrl={imageUrl}/>
                            )
                        )
                    }


                </div>
                {
                    coffeeStoresFromState.length>0 &&(
                        <div className={"m-t-8"} >
                            <h2 className="heading-secondary ">Coffee Shops near you</h2>
                            <div className="card-layout m-t-4 ">
                                {

                                    coffeeStoresFromState.map(
                                        ({id, name, imageUrl}) => (
                                            <Card key={id} name={name} href={`/coffee-store/${id}`}
                                                  imageUrl={imageUrl}/>
                                        )
                                    )
                                }


                            </div>
                        </div>
                    )
                }

            </main>
        </div>
    );
}
