import Head from "next/head";
import Image from "next/image";

import Banner from "../components/banner.component";
export default function Home() {
  const handleOnBannerButtonClick = () => {
    console.log("Banner Button Clicked");
  };
  return (
    <div className="home-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home-page__main">
        <Banner
          buttonText={"View Stores nearby"}
          handleOnClick={handleOnBannerButtonClick}
        />

      </main>
    </div>
  );
}
